spring:
  application:
    name: userManagement

  datasource:
    url: jdbc:mysql://localhost:3306/userdetails?useSSL=false
    username: root
    password: password@123

  jpa:
    show-sql: true
    hibernate:
      #dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update


